name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y libgtest-dev cmake
    - name: Build tests
      run: cmake -S . -B build -DBUILD_TESTS=ON && cmake --build build
    - name: Run tests
      run: ./build/test/unit_tests
