//
// Created by Maksim on 26.04.2023.
//

#ifndef TRIANGLE_INTERSECTIONS_CONSOLE_INTERACTION_H
#define TRIANGLE_INTERSECTIONS_CONSOLE_INTERACTION_H

namespace Interaction {
}

#endif //TRIANGLE_INTERSECTIONS_CONSOLE_INTERACTION_H
