name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -B build -S .
    - name: Build
      run: cmake --build build
    - name: Run tests
      run: ./build/unit_tests
